SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
MAX_ASTEROIDS = 10
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 200
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3
PLAYER_ACCELERATION = 200

SHOT_RADIUS = 5
